---
- include_tasks: cleanup-RedHat-9-fallback-traces.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('9', '==') and not docker_yum_repo_url_fallback_to_8|bool

- include_tasks: setup-RedHat-9.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('9', '==') and docker_yum_repo_url_fallback_to_8|bool

- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version is version('9', '<') or not docker_yum_repo_url_fallback_to_8|bool

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Suse.yml
  when: ansible_os_family == 'Suse'

- name: Include Suse-specific variables
  include_vars: Suse.yml
  when: ansible_os_family == 'Suse'

- name: Ensure containerd is installed.
  package:
    name: "{{ containerd_package }}"
    state: "{{ containerd_package_state }}"

- name: Ensure containerd is started and enabled at boot.
  service:
    name: containerd
    state: "{{ containerd_service_state }}"
    enabled: "{{ containerd_service_enabled }}"

- name: Ensure containerd config directory exists.
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  register: containerd_dir

- name: Deploy containerd config
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml-test
    owner: root
    group: root
    mode: "644"
  notify: restart containerd

- name: Ensure crictl config exists.
  stat:
    path: /etc/crictl.yaml
  register: containerd_crictl_config

- name: Create empty crictl config file
  file:
    path: /etc/crictl.yaml
    state: touch
    mode: '0644'
  when: not containerd_crictl_config.stat.exists

- name: Fill crictl config file
  lineinfile:
    line: "runtime-endpoint: unix:///run/containerd/containerd.sock"
    path: /etc/crictl.yaml
  when: not containerd_crictl_config.stat.exists

- name: Cleanup temporary file
  file:
    path: /tmp/containerd_config.toml
    state: absent
  changed_when: false

- name: Ensure containerd is restarted immediately if necessary.
  meta: flush_handlers
